import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import gql from "graphql-tag";
import { useQuery } from "@apollo/client";
import { Post } from "@/data/data";
import AddPost from "@/components/AddPost";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const { data, loading, error } = useQuery(gql`
    query Posts {
      posts {
        id
        title
        likes
      }
    }
  `);
  console.log({ data, loading, error });

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <AddPost />
        {data &&
          data.posts.map((post: Post) => (
            <>
              <h1>{post.title}</h1>
            </>
          ))}
      </main>
    </>
  );
}
