import Head from "next/head";
import { Inter } from "next/font/google";
import { useQuery } from "@apollo/client";
import AddPost from "@/components/AddPost";
import { graphql } from "@/graphql/client";
import { Box, List, ListItem } from "@mui/material";

const inter = Inter({ subsets: ["latin"] });

const GET_POSTS = graphql(/* GraphQL */ `
  query Posts {
    posts {
      title
    }
  }
`);

export default function Home() {
  const { data, loading, error } = useQuery(GET_POSTS);
  console.log({ data, loading, error });

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${inter.className}`}>
        <AddPost />
        <Box>
          {data && data.posts && (
            <>
              <List>
                {data.posts.map((post) => {
                  return (
                    <>
                      <ListItem key={post?.title}>{post?.title}</ListItem>
                    </>
                  );
                })}
              </List>
            </>
          )}
        </Box>
      </main>
    </>
  );
}
